/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test.jaeger;

import javax.ws.rs.ApplicationPath;
import javax.ws.rs.core.Application;

@ApplicationPath("/")
public class App extends Application {
}